[context.production]
  command = "npm run build"
  publish = "build"
  environment = { API_BASE_URL = "https://app.genioreis.com/api" }

[context.staging]
  command = "npm run build"
  publish = "build"
  environment = { API_BASE_URL = "https://stage.genioreis.com/api" }